version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017/alternance-db
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - alternance-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - alternance-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alternance-network

networks:
  alternance-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
